--- 
title: "SHEDS Stream Temperature Model"
author: "Jeffrey D Walker, PhD"
date: "v0.9.1 (Jun 6, 2018)"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: walkerjeffd/sheds-streamtempmodel
description: "Documentation for the SHEDS stream temperature model."
---

```{r setup, echo = FALSE}
library(tidyverse)
source("../functions.R")
config <- load_config("../../")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = NA)
```

# Introduction {#intro}

Welcome to the SHEDS stream temperature model documentation.

This website is provides background and results of the stream temperature model. The documentation will be updated for each new set of results. See the Change Log below for changes from earlier versions.

The source code for the model and documentation is available in the github repository [walkerjeffd/sheds-streamtempmodel](https://github.com/walkerjeffd/sheds-streamtempmodel).

## Model Versioning

The SHEDS stream temperature model uses semantic versioning of the form: `vX.Y.Z`

`X` is the major version, `Y` is the minor version, and `Z` is the patch version.

For the stream temperature model, the `X` value will be incremented when there is a major change to the model theory, code, or datasets. The `Y` value will be incremented when there is a new set of results due to changes in the model code, datasets, processing procedures, etc. The `Z` value will be incremented when only the documentation or output datasets are updated, but the results remain the same (based on the `Y` value). 

## Changelog

- **[v0.9.1 (Jun 6, 2018)](http://ecosheds.org/models/stream-temperature/v0.9.1/)**  
Updates to model versioning and configuration framework, and minor updates to documentation (still incomplete).
- **[v0.9.0 (May 30, 2018)](http://ecosheds.org/models/stream-temperature/v0.9.0/)**  
Preliminary release of the new model framework and documentation.
- **[Previous Versions](http://conte-ecology.github.io/conteStreamTemperature_northeast/) (prior to 2018)**  
Previous versions of the stream temperature model can be found [here](http://conte-ecology.github.io/conteStreamTemperature_northeast/). That website is now deprecated, but will remain available for future reference. Beginning with v1.0.0 of the new framework and codebase, all model changes and results will be tracked and made available.

